---

#
# Add/Update APT repository
#

- name: Debian | Add APT repo for openjdk 8
  apt_repository:
    repo: deb http://http.debian.net/debian jessie-backports main
    state: present

- name: Debian | Install WebUpd8 APT key
  apt_key:
    id: EEA14886
    keyserver: keyserver.ubuntu.com
    state: present
  register: get_webupd8_key
  until: get_webupd8_key|success
  retries: 5
  delay: 10

- name: Debian | Add WebUpd8 APT repo
  apt_repository:
    repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
    state: present

- name: Debian | Update APT cache
  apt: 
   update_cache: yes 

#
# Install/Configure Java package(s)
#

- name: Debian | Accept Oracle Java License
  debconf:
    name: "oracle-java8-installer"
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Debian | Ensure Java is installed
  apt:
    name: openjdk-8-jdk
    state: installed
  register: install_java_command

